### ISSUE TITLE
This Script Support only x64 binary???

### ISSUE THREAD

**Issue by simhigo** [amimo/ollvm-breaker#4]
This Script Support only x64 binary???

**Comment by amimo** [comment]
arm64

**Comment by simhigo** [comment]
Are you planning to support arm32 binaries in the future?

**Comment by amimo** [comment]
no. arm32 code is very hard to patch. the apple store & google store are both required 64 bit support, so the need to deobfuscate arm32 may become less in the future.

**Comment by simhigo** [comment]
Thank you for answer. 
Have a nice day :)
