### ISSUE TITLE
没有binja，求解这几句代码的含义

### ISSUE THREAD

**Issue by chago** [amimo/ollvm-breaker#5]
以下选中的代码中，过滤definition的时候固定了address，states的返回值为什么会有长度是2的情况，难道一个地址会有两个definition？

'''
    for definition in state_var.get_definitions(True):
        states = get_var_definitions_at(mlil, definition.dest, definition.address)
'''

**Comment by amimo** [comment]
csel会定义至少两个state.下面的w7有两个state.
```asm
csel    w7, w4, w17, eq  {0xce5376fa}  {0xa44bdc68}
```
这里有相关的原理，你可以看看：https://bbs.pediy.com/thread-256299.htm

**Comment by chago** [comment]
明白，谢谢大佬
